### ISSUE TITLE
Include shaders and a default configuration file in the nightly releases

### ISSUE THREAD

**Issue by byuu** [bsnes-emu/bsnes#1]
The official bsnes releases ship with a default configuration file and shaders. It would be ideal to grab the settings.bml file from the bsnes v115 release, and ensure that this and the shaders appear inside nightly release builds.

**Comment by Screwtapello** [comment]
bsnes nightly releases should (now) contain shaders, although we should probably re-confirm that they're actually available and working (do they have the right name? does bsnes default to OpenGL so shaders are available?).

bsnes does *not* currently include a `settings.bml` file, and it should. higan has `extras/byuu/settings.bml` that it ships with nightly builds of the simple UI, bsnes should do something similar.
