### ISSUE TITLE
hiro gtk3: Black menu bar

### ISSUE THREAD

**Issue by Screwtapello** [bsnes-emu/bsnes#108]
When building bsnes with `hiro=gtk3`, the menu-bar is drawn as normal (usually dark-grey) text on a black background, instead of the (usually light-grey) background the theme provides.

I have no idea why it does this, but this is a blocker for making GTK3 the default hiro backend.

**Comment by ghisvail** [comment]
I have a feeling that [setBackgroundColor](https://github.com/bsnes-emu/bsnes/blob/083406f404f52d94c80cd8ac23f66b34a1cc4fd7/hiro/gtk/window.cpp#L177) applies to the whole window on GTK3 (including the menu bar attached to it), whilst it does not on GTK2.

**Comment by ghisvail** [comment]
gtk2:

![Capture d’écran de 2020-11-20 09-34-11](https://user-images.githubusercontent.com/1964655/99778363-e1f16a00-2b13-11eb-9316-c81d5bc4beae.png)

gtk3:

![Capture d’écran de 2020-11-20 09-35-25](https://user-images.githubusercontent.com/1964655/99778370-e4ec5a80-2b13-11eb-9523-2012742aed47.png)

as compiled on Debian 10.

**Comment by ghisvail** [comment]
I asked GNOME/gtk on IRC and they explained that GTK3 widgets are transparent by default. Using the GTK inspector I was able to verify this. Possible solutions are either to set the background window to black or set the background color of the menu bar to a different color explicitly.

**Comment by asuramaru** [comment]
I'm not trying to be a thorn in your side. Your patch will break the menubar matching dark themes for me. I don't get the black menubar issue you do. The menubar isn't transparent for me. It seems the transparency is theme-depenedent or something. I'll try to look into this then.

**Comment by Screwtapello** [comment]
Thank you to @ghisvail and @asuramaru for the time you have spent investigating this issue and considering different approaches to solving it, and I apologise for how long it's taken for me to review your respective PRs.

I'd like to avoid solutions that involve explicitly setting the background of the menubar to what it "should" be, because that's going to change from version to version and I'd rather not have to keep chasing that. For example, the implementation in #118 works nicely for the GNOME 3 standard *Adwaita*, *Adwaita-dark*, *HighContrast* and *HighContrastInverse* themes, but does not update if the current theme is changed while bsnes is open. I'm sure it's not too difficult to listen for theme-change notifications and update the background colour, but that was literally the first thing I tried that caused a problem. I'm sure there's other corner cases, either now or in the future.

Instead, I propose just *not* setting the window background colour, in #126. It's a much simpler change, should be much more compatible with GTK+3, and hopefully does not introduce too many regressions on other backends. I know it makes the resize-flickering inherent to GTK+2 more noticable, I'll be interested to hear what effect it has on Windows or macOS.

**Comment by ghisvail** [comment]
> Instead, I propose just not setting the window background colour

Funny, that's exactly what the GTK folks on IRC suggested in the first place :smile:

**Comment by Screwtapello** [comment]
My fix in #126 was insufficient - it left a pale rectangle in the lower-right beside the bsnes icon when no game was loaded. I tried to teach `hiro::Canvas` about a padding-colour for "draw an icon" mode, but tinkering with all the platform backends got me in over my head.

And so now, #127 adds a new spacer canvas to cover the rectangle in the lower-right, which should look identical, but means the GTK+3 menu bar looks correct and responds to theme-updates, etc.
