### ISSUE TITLE
Air Strike Patrol shadow not rendering correctly

### ISSUE THREAD

**Issue by JuanchoES** [bsnes-emu/bsnes#114]
Video reference https://youtu.be/LOSQgBEf5ac?t=714

Edit: I have find this comment on the comments of the youtube video "The Air Strike Patrol shadow discrepancy is not due to anything wrong with the NT or Higan. Rather it’s an issue with the design of Nintendo’s own 1CHIP revision of the system. Both Higan and the NT reproduce the shadow like an original SNES would, it’s the single-chip model that is bugged (albeit very slightly)."

Idk if this glitch can be solved.

**Comment by Screwtapello** [comment]
Using the latest nightly build of bsnes:

![image](https://user-images.githubusercontent.com/1450918/99651054-3e1fa400-2aaa-11eb-83ff-acc6ceb25111.png)

As you can see, the shadow is visible to the right of the palm-tree underneath the plane. Does it not appear on your copy of bsnes?

**Comment by JuanchoES** [comment]
> Using the latest nightly build of bsnes:
> 
> ![image](https://user-images.githubusercontent.com/1450918/99651054-3e1fa400-2aaa-11eb-83ff-acc6ceb25111.png)
> 
> As you can see, the shadow is visible to the right of the palm-tree underneath the plane. Does it not appear on your copy of bsnes?

Yea, i can see the weird shadow in the nightly build, this is how the shadow should render 
![image](https://user-images.githubusercontent.com/70743149/99658552-f2480d00-2a5f-11eb-88e2-b126dbe9bd27.png)

**Comment by Screwtapello** [comment]
When the video shows "real hardware", the faint shadow suggests they're using the 1CHIP variant. bsnes (and higan) emulate the original SNES console, not the 1CHIP, so I don't think there's anything to fix here.

> Btw, this is the only game that i ever played that lags in my bsnes lol

This is the only game where bsnes force-enables Accurate PPU mode. For every other game, bsnes stays in Fast PPU mode unless you switch it manually.

**Comment by Max833** [comment]
For the sake of completeness, on my original hardware the shadow looks pretty much like bsnes. So yeah, there is no bug.
