### ISSUE TITLE
USB to SNES gamepads adapter

### ISSUE THREAD

**Issue by asheenlevrai** [bsnes-emu/bsnes#124]
Hello :)

I recently purchased this USB adapter in order to connect OEM SNES gamepads to my iMac running bsnes v115.
https://www.amazon.com/Mcbazel-Controller-Android-PC-Adapter-Converter/dp/B07GJV2PTL/ref=sr_1_1?dchild=1&keywords=Mcbazel+2+player+SNES-Controller+for+Steam%2C+Android%2C+PC%2C+MAC+OS&qid=1607590682&sr=8-1

It seemed to work since I can assign buttons normally via the tool in _Proprieties_ (both ports of the adapter seem to trigger the same thing so I guess it's going to be 1 player only, but that is another topic I suppose).

Now, in game, none of the buttons of the SNES gamepad trigger anything (or at least I'm stuck when I need to press START).

How can I troubleshoot this?
Is the adapter outright incompatible for some reason?
Or do I need a specific macOS driver as mentioned in the description of the adapter on Amazon : "(NOTE: extra driver may be required on Mac, which is NOT included)"

Thank you very much in advance for your help.
Best,
-a-

**Comment by Screwtapello** [comment]
You asked this the other day in Discord, and I answered there, but I guess you must have missed it. To repeat:

- If you can assign buttons in Preferences → Input, your adapter already works as well as it can be expected to, and no additional or alternate drivers are needed
- In Preferences → Input, there should be a drop-down list labelled "Port" (defaulting to "Controller Port 1") and another labelled "Device" (defaulting to "Gamepad". This means "if a Gamepad controller is connected to Controller Port 1, these keys/gamepad buttons should be mapped to buttons on the emulated controller"
- However, if a Gamepad controller is *not* connected to Controller Port 1, these mappings are ignored
- In the "System" menu, there should be sub-menus for Controller Port 1 and Controller Port 2, which allow you to change what kind of device is connected to each controller port
- Make sure the devices connected to the Controller Ports are the devices you've actually mapped in Preferences → Input

**Comment by asheenlevrai** [comment]
I tried again and it works now.
This time the LED on the adapter lit up. It dint previously.
Also the adapter is detected as a keyboard somehow.
During buttons mapping gamepad 1 mapping goes as usual while when I map gamepad 2, they buttons assigned are keyboard keys. I guess the 2nd gamepad is detected as a keyboard. It work though.

Thanks a lot.
(The adapter doesn't work on my Android TV, though. I mean it does something but it so buggy that it is unusable (especially for the 2nd gamepad. I guess this cheap thing is a cheap thing...)

Best,
-a-
