### ISSUE TITLE
Rock n' Roll Racing - Black Screen after select a character

### ISSUE THREAD

**Issue by Shideravan** [bsnes-emu/bsnes#125]
After select a character, the game freezes in black screen.
I'm using the lastly nightly build (2020-11-12).

**Comment by Max833** [comment]
I can't reproduce this issue. It works perfectly. 
What settings do you have in this window? 

![image](https://user-images.githubusercontent.com/53529402/102024966-3e534c80-3d95-11eb-971d-c79f31e8e7d1.png)

**Comment by Screwtapello** [comment]
Also, what shader are you using? What are the first few lines of the manifest in Tools → Manifest Viewer?

**Comment by Shideravan** [comment]
It's was caused by overclock configurations. In 100% it's working normal.

**Comment by Screwtapello** [comment]
Ah, glad to hear you got it sorted!
