### ISSUE TITLE
Relative Folder Paths possible?

### ISSUE THREAD

**Issue by A-Force-For-Change** [bsnes-emu/bsnes#128]
Is it possible to specify relative folder paths for all the folders (games-folder, saves-folder, ...)?

**Comment by JuanchoES** [comment]
![image](https://user-images.githubusercontent.com/70743149/103161060-d06b4400-47dc-11eb-9a9d-5049dfdde3a2.png)
yes, its not that hard to find lol

**Comment by Kawa-oneechan** [comment]
> yes, its not that hard to find lol

I see no relative paths there, only absolutes. If relative paths are possible, that would certainly be where you'd set them, but *are they supported to begin with?*

**Comment by Kawa-oneechan** [comment]
Now, the actual text fields in that dialog box are _locked_. You can only change their values through their respective Assign and Reset buttons. That means you can only set them to absolute paths!

But what if you edited those path settings manually, by opening settings.bml in a text editor? I changed my *Games* path to `..` and restarted bsnes. Opening a game started me out in bsnes' parent folder, as `..` should.

So yeah. It's possible, but not from the UI.

**Comment by Screwtapello** [comment]
Like `paths.bml` for higan, that probably makes the path relative to the current directory when higan was started, not necessarily relative to the directory containing the higan executable, so setting the SRAM location to a relative path in `settings.bml` will probably work fine 90% of the time and cause your game saves to vanish occasionally for no good reason, and come back later.

`nall::path` needs to be taught about resolving paths relative to a specific context, not just "whatever the working directory happens to be" and this part of bsnes needs to be updated to use those APIs when they become available.

**Comment by A-Force-For-Change** [comment]
> Now, the actual text fields in that dialog box are _locked_. You can only change their values through their respective Assign and Reset buttons. That means you can only set them to absolute paths!

I just found out that relative paths are possible via the UI, too.
Click 'Assign', type the relative path in the top field, **press 'Enter'**, click 'Select'.

> Like `paths.bml` for higan, that probably makes the path relative to the current directory when higan was started, not necessarily relative to the directory containing the higan executable, so setting the SRAM location to a relative path in `settings.bml` will probably work fine 90% of the time and cause your game saves to vanish occasionally for no good reason, and come back later.
> 
> `nall::path` needs to be taught about resolving paths relative to a specific context, not just "whatever the working directory happens to be" and this part of bsnes needs to be updated to use those APIs when they become available.

That means this issue has to be re-opened?

**Comment by Screwtapello** [comment]
There's not really anything we can do about this issue right now, so I'll leave it closed, but I've added the "later" label so we can find it again if things change.
