### ISSUE TITLE
Update `boards.bml` database

### ISSUE THREAD

**Issue by Screwtapello** [bsnes-emu/bsnes#13]
bsnes currently uses a copy of the `boards.bml` database from 2018, while higan's copy was updated in 2020 and includes more entries.

`boards.bml` is an actual file in the repo, but I don't think the bsnes compilation process uses that file directly - I think there's an additional, manual step of encoding it into a C++ source file that can be built into the bsnes binary, probably using the [sourcery](https://github.com/higan-emu/higan/tree/master/sourcery) tool.

**Comment by RokkumanX** [comment]
@Screwtapello 

I have made some pull requests that could be of some interest for you in this regard.
