### ISSUE TITLE
hiro: do not require gtksourceview-2.0

### ISSUE THREAD

**Issue by Screwtapello** [bsnes-emu/bsnes#137]
By default, bsnes builds hiro with support for the `SourceEdit` control, which (in GTK+2 builds) is implemented on top of the `gtksourceview-2.0` library. While GTK+2 itself widely used enough to be around for a long time, `gtksourceview-2.0` [has already been removed from Debian Testing](https://tracker.debian.org/news/1173790/gtksourceview2-removed-from-testing/), so removing our dependency on this library is important.

It turns out that bsnes does not actually *use* the `SourceEdit` widget, so it shouldn't be too hard to make hiro build without it, at least for GTK+2 builds. Alternatively, we could just make GTK+3 the default backend on POSIX, with the same effect.

(GTK+3 builds currently depend on the `gtksourceview-3.0` library, which has *also* been deprecated in favour of `gtksourceview-4.0` — still based on GTK+3 — but that's a job for a different issue)

**Comment by orbea** [comment]
I made a PR that disables the dependency everywhere when building bsnes. https://github.com/bsnes-emu/bsnes/pull/139
