### ISSUE TITLE
PPU Accuracy: The Final Piece Of The Puzzle?

### ISSUE THREAD

**Issue by Michael-Prince-Sharpe** [bsnes-emu/bsnes#138]
I read a while ago about PPU behaviour not being entirely known as described in this article https://arstechnica.com/gaming/2020/04/how-snes-emulators-got-a-few-pixels-from-complete-perfection/

I found that PPU1 and PPU2 have now been decapped with their respective die scans here
http://www.siliconpr0n.org/map/nintendo/s-ppu1-5c77-01/
http://www.siliconpr0n.org/map/nintendo/s-ppu2-5c78-01/
http://www.siliconpr0n.org/map/nintendo/s-ppu2-b-5c78-03/

I also found out that PPU logic analyser is being developed here
https://github.com/khaydarian/spla

Is any of this any help to filling in the final piece of the SNES preservation and emulation puzzle?

**Comment by Screwtapello** [comment]
Yes it is! When Near wrote that original Ars Technica article, he added a #technica channel to the official bsnes discord, where people are studying those die-scans and turning them into circuit diagrams. When that work is complete, hopefully I (or somebody else) will be able to update the higan and bsnes PPU emulation to match.

Thanks for creating an issue; if you'd like to get involved there's a permanent link to the discord on https://byuu.org/bsnes/

**Comment by shaneallgeier** [comment]
Hey @Screwtapello, is there a more recent discord invite link? byuu.org is down now and the one from bsnes.dev (https://discord.com/invite/2Yj88Yk) is no longer valid.

Thanks!

**Comment by Screwtapello** [comment]
Unfortunately, since Near died we no longer have access to update https://bsnes.dev, I've made a PR to add an updated Discord invite link to the README. The PR will probably be merged in the next day or two, but you can go grab the invite link right now: https://github.com/bsnes-emu/bsnes/pull/191/files
