### ISSUE TITLE
Interlacing issue in accurate PPU

### ISSUE THREAD

**Issue by Michael-Prince-Sharpe** [bsnes-emu/bsnes#159]
When using the crt-royale or crt-royale-kurozumi shaders it's very noticeable with jittery flickering interlacing. The accurate PPU seems to think it's interlaced. This doesn't happen on the fast PPU.

**Comment by Screwtapello** [comment]
A real SNES can output frames that are 256×240, 256×480, 512×240, or 512×480 pixels in size (it's always 4:3, but the pixel aspect ratio differs). Most traditional SNES emulators (ZSNES, Snes9x, the bsnes fast PPU) decide on a size at the beginning of each frame, render that many pixels, then hand the frame over to the GPU shader. As a result, many shaders will guess whether a frame is supposed to be progressive or interlaced with a simple test like `height > 240`.

However, a real SNES doesn't work like that - in particular, the "256 or 512 pixels wide" setting can be toggled multiple times per frame, resulting in some lines that are 256px wide, and some that are 512px wide, and that's *not* a configuration shaders are built to handle. While it's not technically possible to toggle interlaced mode at the beginning of a frame, for consistency and simplicity of implementation the accurate PPU just renders *every* frame as 512x480, pixel-doubling or quadrupling where necessary.

Which is to say: this is working as designed. It would be nice if interlacing played more nicely with shaders, but given that 99.9% of games work perfectly in fast PPU mode, it's not worth the effort to fix.
