### ISSUE TITLE
Full crash when entering boss level Super Mario World

### ISSUE THREAD

**Issue by ineeni** [bsnes-emu/bsnes#165]
Full crash complete exit when entering Super Mario World Castle 1 boss room.  

Emulator v115
Rom: Super Mario All-Stars & World (E) [!]
Current Config:
Video
  Driver: OpenGL 3.2
  Exclusive: false
  Blocking: false
  Flush: false
  Monitor: 1: CHG9_C49HG9xDM (DP)
  Format: ARGB24
  Shader: None
  Luminance: 100
  Saturation: 100
  Gamma: 150
  Dimming: true
  Snow: false
  Output: Scale
  Multiplier: 4
  AspectCorrection: false
  Overscan: false
  Blur: true
  Filter: None
Audio
  Driver: waveOut
  Exclusive: false
  Device: Default
  Blocking: true
  Dynamic: false
  Frequency: 44100
  Latency: 128
  Mute: false
  MuteUnfocused: false
  Skew: 0
  Volume: 100
  Balance: 50
Input
  Driver: Windows
  Frequency: 5
  Defocus: Block
  Turbo
    Frequency: 4
  Hotkey
    Logic: or
Path
  Games
  Patches
  Saves
  Cheats
  States
  Screenshots
  Recent
    SuperFamicom: C:/Users/ineen/OneDrive/Desktop/bsnes_v115-windows/
    GameBoy
    BSMemory
    SufamiTurboA
    SufamiTurboB
FastForward
  FrameSkip: 9
  Limiter: 0
  Mute: false
Rewind
  Frequency: 0
  Length: 80
  Mute: false
Emulator
  WarnOnUnverifiedGames: false
  AutoSaveMemory
    Enable: true
    Interval: 30
  AutoSaveStateOnUnload: false
  AutoLoadStateOnLoad: false
  Hack
    Hotfixes: true
    Entropy: Low
    CPU
      Overclock: 100
      FastMath: false
    PPU
      Fast: true
      Deinterlace: true
      NoSpriteLimit: false
      NoVRAMBlocking: false
      Mode7
        Scale: 4
        Perspective: true
        Supersample: false
        Mosaic: true
    DSP
      Fast: true
      Cubic: false
      EchoShadow: false
    Coprocessor
      DelayedSync: true
      PreferHLE: false
    SA1
      Overclock: 100
    SuperFX
      Overclock: 100
  Cheats
    Enable: true
  Serialization
    Method: Fast
  RunAhead
    Frames: 0
General
  StatusBar: true
  ScreenSaver: false
  ToolTips: true
  Crashed: false
  BetaWarning: false
  NativeFileDialogs: false
Hotkey
  ToggleFullscreenMode: 0x1/0/11
  ToggleMouseCapture: 0x1/0/12
  ToggleCheatCodes
  ToggleMute
  Rewind: 0x1/0/28
  SaveState: 0x1/0/69
  LoadState: 0x1/0/71
  LoadUndoState
  LoadRedoState
  IncrementStateSlot: 0x1/0/6
  DecrementStateSlot: 0x1/0/8
  CaptureScreenshot
  FastForward: 0x1/0/15
  PauseEmulation: 0x1/0/50
  FrameAdvance: 0x1/0/27
  IncreaseHDMode7
  DecreaseHDMode7
  ToggleSupersampling
  ResetEmulation
  QuitEmulator
  ToggleFullscreen: 0x1/0/11
  TogglePseudo-Fullscreen
Game
  Recent
    1: Auto;C:/Users/ineen/OneDrive/Desktop/bsnes_v115-windows/Super Mario All-Stars & World (E) [!].smc

**Comment by Kawa-oneechan** [comment]
With the *second-to-last* nightly, I just played all the way through to Iggy's Castle and got through the whole thing.

I fully expect the very latest nightly that just came out to work as well.

**Comment by ineeni** [comment]
That did it, was able to make it past with save state too.
