### ISSUE TITLE
Add Support for the Mega Man X3 "Zero Project" Hack (Large Cx4 ROM support)

### ISSUE THREAD

**Issue by Awakened0** [bsnes-emu/bsnes#167]
https://www.romhacking.net/hacks/4086/

Currently launching this hack results in a black screen in bsnes. It runs on real hardware, but only on flashcarts that support it since it requires larger Cx4 ROM support.

**Comment by Screwtapello** [comment]
Looking at the github repo for that hack, it includes [an XML manifest for older versions of bsnes](https://github.com/justin3009/MMX3-ZeroProject/blob/master/Mega%20Man%20X3%20(Manifest%20for%20BSNES)%20%5BRENAME%20TO%20ROM%20NAME%20IN%20ROM%20FOLDER%5D.xml). Presumably if that were converted to the modern BML format, that would also get the hack working without requiring any changes to bsnes itself.

I don't have the time to do that myself right now, but it should be possible for somebody with romhacking experience to compare the romhack's XML manifest with XML manifest generated for the original game by an old version of bsnes, and then apply similar changes to a modern BML manifest for the original game.

**Comment by Awakened0** [comment]
I'll close this as it seems more on the patch to distribute the manifest and I have an issue open on it's repo to add a BML version: https://github.com/justin3009/MMX3-ZeroProject/issues/7
