### ISSUE TITLE
PPU Accuracy

### ISSUE THREAD

**Issue by sharknnth** [bsnes-emu/bsnes#18]
In this article, Byuu mentions that the PPUs aren't fully documented and understood yet.
https://byuu.org/articles/edge-of-emulation

I found the documentation from the Official Software Development Kit of the Super Nintendo if that's of any help to Byuu and others in the emulation community? It's got quite a lot f information on the PPUs [THIS LINK REMOVED FOR ETHICAL AND LEGAL REASONS.]

**Comment by Kawa-oneechan** [comment]
I haven't looked at these docs before I removed your link, but Merry and I sincerely doubt it has the kind of in-depth information we're after.

**Comment by Screwtapello** [comment]
Just to add a little more detail, while I also haven't seen the documentation in question, I know there's a lot of Official SDK docs floating around for various consoles, and from what I've heard, they're really focussed on writing games, they don't contain enough information to write a decent emulator, and they definitely don't contain the sort of low-level information bsnes needs to be complete. The games that followed the instructions in the SDK all work perfectly in bsnes; it's the games that break the SDK's rules that we're having trouble with.

It's possible there's Nintendo documentation about this stuff, but if it existed it would probably only be internal design documentation (from when the PPUs were being designed and tested) or very recent emulator documentation (from when Nintendo started writing their own emulators for the Virtual Console, etc.). Either way, though, the SDK docs aren't it.

Thank you very much for the offer, though!

**Comment by Kawa-oneechan** [comment]
I have in fact looked, and it's exactly the same docs that I thought it'd be and have seen before.
