### ISSUE TITLE
[Feature Request] Netplay support

### ISSUE THREAD

**Issue by Toadfield** [bsnes-emu/bsnes#185]
it would be fucking cool to be able to play snes games with hd mode 7 and widescreen online.
I know I can use something like persec,but I don't have money and it would be cool to be able to create lobbies and stuff like that.

**Comment by Kawa-oneechan** [comment]
1. Widescreen is in the bsnes-hd fork, not here.
2. Netplay desynchronization is a serious issue, especially in emulation, and moreso with _heavy_ emulators like bsnes. It's almost unavoidable, I'd dare to say.

**Comment by Toadfield** [comment]
> Widescreen is in the bsnes-hd fork, not here.

But when you add a feature to bsnes,then it will also be in bsnes-hd,that's what I meant
>Netplay desynchronization is a serious issue, especially in emulation, and moreso with heavy emulators like bsnes. It's almost unavoidable, I'd dare to say.

Would it really be worse than using parsec or something like that?

**Comment by Kawa-oneechan** [comment]
> But when you add a feature to bsnes,then it will also be in bsnes-hd,that's what I meant
That will not happen.

> Would it really be worse than using parsec or something like that?
I wouldn't know. All I know is that netcode is *such* an issue in general that there was a whole discussion about it on the discord.
