### ISSUE TITLE
Support integrating newer revisions of Sameboy as they release.

### ISSUE THREAD

**Issue by Yersho** [bsnes-emu/bsnes#19]
I don't know if you are already doing this or not but I was wondering if you plan on integrating future revisions of Sameboy into the emulator for it's Super Game Boy emulation. Sameboy is only on revision 0.12.3 so it would make sense to update BSNES's Sameboy core as new releases come out.

**Comment by Screwtapello** [comment]
It looks like currently [`bsnes/bsnes/gb/`](https://github.com/bsnes-emu/bsnes/tree/30e274953a8d7dc10e71be0987c15018e397df2f/bsnes/gb) is a manually-stripped-down copy of [SameBoy's source structure](https://github.com/LIJI32/SameBoy/tree/ddad913e06fb51e80957177d404fef3d1d3b5d6c).

In *theory* we should be able to just make that directory a git subtree of SameBoy and pull updates whenever we like... but it *would* be messier and more confusing to have the entire SameBoy source-tree and build-system included when we use hardly any of it. I'm also not entirely sure how to *test* bsnes after updating SameBoy, other than just "does Donkey Kong '94 run".

**Comment by Screwtapello** [comment]
To actually answer your question, though: I would like to keep bsnes' bundled version of SameBoy up-to-date, it's just a matter of figuring out what needs to be done, and finding the time to do it.

**Comment by LIJI32** [comment]
0.12.3 is the latest stable version of SameBoy, bsnes shouldn't use a non-stable version (As the save state format varies between revisions, and stable releases expect save state from other stable releases). Also, byuu and I took care of making sure all of bsnes' changes to SameBoy are either reintegrated or reimplemented in a way that does not require changes to the core, so updating SameBoy is just a matter of copying a new `Core` directory from SameBoy over the old one.

**Comment by RokkumanX** [comment]
bsnes is currently updated with SameBoy 0.13.1 and nothing overly important have happened after, is that enough?

**Comment by LIJI32** [comment]
0.13.2 fixed a few bugs related to save states. Specifically, it fixed a case where save states from Windows did not work on other OS and vice versa.

**Comment by RokkumanX** [comment]
Glad to see some response, I thought everyone died.

So updating the core isn't that hard right? Maybe I should attempt it and see what happens.

**Comment by RokkumanX** [comment]
OK I made some commits but I couldn't find anywhere to change 0.13.1 to 0.13.2

You should be able to change files and only make one commit, but that's beyond my knowledge.
