### ISSUE TITLE
Someone here maybe screwtape is byuu near really gone?

### ISSUE THREAD

**Issue by Eggo-dotcom** [bsnes-emu/bsnes#193]
Is the news true?

I really hope not. I have been so busy last few tears that i float in and out of the internet….

finding out byuu aka near is gone is very upsetting. I know this is an odd place to ask but i dont know where to ask since the last place i saw ppl like screwtape was on byuu’s old forum.

i hope what I have read is not true.

**Comment by Screwtapello** [comment]
I'm afraid it is true.

**Comment by Eggo-dotcom** [comment]
Thanks for the reply.

im so sorry for near byuu

Someone who worked so hard on preserving something and no one helped preserve them. This actually makes me sad for them.

**Comment by Screwtapello** [comment]
Lots of people tried to help, in different ways, but in the end it wasn't enough. It's very sad, but we're doing what we can to honour his memory.

**Comment by Eggo-dotcom** [comment]
Yes im sure ppl tried didnt mean it that way. Just sad about it and hope if there is anything after this that byuu found peace. Over the years without knowing this person made my life a little better. Anyway ill be quiet now. Just sorry
