### ISSUE TITLE
Retroarch, gamepad doesn't respond to any buttons 

### ISSUE THREAD

**Issue by megapro17** [bsnes-emu/bsnes#225]
If you open any game in bsnes core in Android, and minimize it, game will not respond to any buttons until app is restarted. This bug doesn't exist in other cores, e.g snes9x. 

1. Open snes game in bsnes core
2. Connect gamepad or maybe keyboard will work too
3. Minimize and open RetroArch
4. Gamepad doesn't work

**Comment by Screwtapello** [comment]
We don't actually know very much about RetroArch (or Android) here, sorry. You'll probably have better luck if you file an issue in the RetroArch issue tracker.

**Comment by megapro17** [comment]
Libretro bsnes repo doesn't has any commits from march...
