### ISSUE TITLE
Cannot download binaries

### ISSUE THREAD

**Issue by drone1** [bsnes-emu/bsnes#258]
Hello.

If I click on 'Download' from the GitHub repo page under ``Nightly Builds``, then click the first item, then ``linux-x86_64-binaries``, then under ``Artifacts`` click the Download arrow icon on the right next to ``bsnes-nightly``, a 22-byte .zip file downloads.

If instead of clicking the download arrow icon I click ``bsnes-nightly`` itself, it displays a file, ``bsnes-nightly.zip``. If I click this, it takes me [here](https://api.cirrus-ci.com/v1/artifact/task/5354289636835328/bsnes-nightly/bsnes-nightly.zip) which displays the following error:

![image](https://user-images.githubusercontent.com/6324796/194954994-4585c4df-73cb-4d16-9fba-a7ad1760c596.png)

Have I missed something or is this broken? Thanks.

**Comment by Screwtapello** [comment]
Yeah, the README needs to be updated. The current best source for bsnes is GitHub itself: https://github.com/bsnes-emu/bsnes/releases/tag/nightly

**Comment by daninthemix** [comment]
> Yeah, the README needs to be updated. The current best source for bsnes is GitHub itself: https://github.com/bsnes-emu/bsnes/releases/tag/nightly

This link is now just the source code. Pretty nuts that up-to-date binaries seem wholly unavailable.

**Comment by Kawa-oneechan** [comment]
I go to the main Releases page and the top item has binaries for the latest nightly right there.

**Comment by daninthemix** [comment]
> I go to the main Releases page and the top item has binaries for the latest nightly right there.

This is all I see - a binary dated 2020:

![image](https://github.com/bsnes-emu/bsnes/assets/1974239/7c89e818-2ac9-41cf-a3ac-e132cbdcda96)

**Comment by Screwtapello** [comment]
You don't see https://github.com/bsnes-emu/bsnes/releases/tag/untagged-e25659fba553c154f4f2 ?

**Comment by Alcaro** [comment]
I can reproduce this issue. There is exactly one release ever, and that link is a 404.

There is a release in the Tags tab (as opposed to the Releases tab) tagged september, but, as daninthemix said, that one only contains source code (though the email announcing that release says it contains three binaries).

**Comment by Screwtapello** [comment]
I just merged another PR, and when the CI finished building, the download link in the README goes to https://github.com/bsnes-emu/bsnes/releases/tag/nightly which is the correct new build with all the pre-built binaries attached.

I'm not sure what was going wrong, but whatever it was, it seems to have cleared up now. Please leave a comment if you still can't download a nightly, with any extra information you can provide, and I'll take another look.
