### ISSUE TITLE
Fullscreen Video Recording Issue

### ISSUE THREAD

**Issue by ScraperMan2002** [bsnes-emu/bsnes#260]
When I use my video recorder (Xbox Game Bar) to record the gameplay in fullscreen, all it records is a black blank screen with the white menu bar. Why is this happening?
![Proof](https://user-images.githubusercontent.com/53280593/202622301-9a3e58d4-45c2-46d1-9272-c9e82b67f3f9.jpg)
![Bad Recording](https://user-images.githubusercontent.com/53280593/202622307-86337872-0212-4bee-ab00-26ea818c123d.jpg)

**Comment by Screwtapello** [comment]
bsnes wants to support running in a window with a menu-bar, etc. It also wants to support exclusive full-screen mode to minimise input latency. Unfortunately, Windows does not allow bsnes to switch between windowed and full-screen-exclusive mode, so when you switch to full-screen mode, bsnes creates a whole other window and makes *that* exclusive instead.

If you're telling your capture software "capture this window" and pointing at the window with the menu-bar, that's not the window that shows the game in full-screen mode.

If you're telling your capture software "capture the output of this monitor" and it still doesn't work, I'm not sure what else you can try.

**Comment by ScraperMan2002** [comment]
Issue is resolved. Thank you.

**Comment by ScraperMan2002** [comment]
Actuall
