### ISSUE TITLE
Treasure Conflix glitch graphics

### ISSUE THREAD

**Issue by Fortranm** [bsnes-emu/bsnes#262]
![image](https://user-images.githubusercontent.com/19356108/202892779-49fd9554-f441-4f49-adc4-24c1d77e82e6.png)
![image](https://user-images.githubusercontent.com/19356108/202892800-22f0b7b1-1129-4609-b8af-89e86503a310.png)

**Comment by Screwtapello** [comment]
What's the SHA1 hash of your ROM? Are you applying any patches? What part of the game does this occur in? Does it occur every time you get to this part of the game? If so, can you provide an in-game save (not a save-state) near to this moment?

**Comment by carmiker** [comment]
If you're working with an unpatched, vanilla .bs ROM, you'll need to load the BS-X BIOS ROM before Treasure Conflix for correct functionality. If you simply load the .bs file directly, this is the result you'll get.

**Comment by Fortranm** [comment]
> What's the SHA1 hash of your ROM? Are you applying any patches?
Treasure Conflix (Japan) (BS)
SHA1:EAECEB99FE7CAEDB01C2E137669CB05AEFB60944
MD5:B98F45ED397C09FF4D6E51DAEB11C1BE
This is considered a good dump by the gamddb I find. I didn't deliberately apply patches.

> What part of the game does this occur in? Does it occur every time you get to this part of the game? If so, can you provide an in-game save (not a save-state) near to this moment?
This happens at the very beginning of the game after pressing Start at the title screen.

> If you're working with an unpatched, vanilla .bs ROM, you'll need to load the BS-X BIOS ROM before Treasure Conflix for correct functionality. If you simply load the .bs file directly, this is the result you'll get.
![image](https://user-images.githubusercontent.com/19356108/202922805-8bd39252-595e-45a1-a5a6-aed91a65011e.png)
Like this? This shows up after I load the BS-X BIOS (Sore wa Namae o Nusumareta Machi no Monogatari).
I chose the Treasure Conflix rom (.sfc with SHA1 value mentioned above) but it then just proceeded with the default BS-X BIOS content. Is this expected? What should I do to proceed if that's the case?

**Comment by carmiker** [comment]
You will see the BS-X BIOS bootup, and enter into a game where you will select your avatar, name it, etc. Then you just walk into the house closest to you and select all the first options in the menu system until the game starts. This is the same procedure as for all other BS-X games.

**Comment by Fortranm** [comment]
That worked. Thanks.
