### ISSUE TITLE
Flatpak does not list shaders

### ISSUE THREAD

**Issue by Sunspark-007** [bsnes-emu/bsnes#265]
In the menu for Shaders, it just lists None or Blur.

I verified in the settings that it is set for OpenGL 3.2 and it is.

I navigated into the flatpak's directory in /var/lib to determine if the shader files are included in the flatpak and they are.

The issue being reported here is that the flatpak cannot see the shaders it comes with despite being in OpenGL mode.

**Comment by Screwtapello** [comment]
We are not responsible for the Flatpak packaging for bsnes, please report issues to the Flatpak repository: https://github.com/flathub/dev.bsnes.bsnes

**Comment by Sunspark-007** [comment]
I have done so now. Thank you for providing a link as I did not know of this repository before.
