### ISSUE TITLE
bsnes-emu/bsnes Cirrus CI builds failing

### ISSUE THREAD

**Issue by RokkumanX** [bsnes-emu/bsnes#27]
Hi

When I saw that bsnes had been updated with the latest SameBoy my heart skipped a beat but it appears the [buildbot](https://cirrus-ci.com/github/bsnes-emu/bsnes/master) is failing building Windows binaries.

What causes the builds to fail and is there a kindhearted soul out there that have managed to build the latest bsnes with all commits up to https://github.com/bsnes-emu/bsnes/commit/f98cb01d0ab1d791d52039515f7300429f72bdd5

Many thanks in advance!!

**Comment by Kawa-oneechan** [comment]
I have literally *just* built bsnes for Windows with the latest commits: [bsnes.zip](https://github.com/bsnes-emu/bsnes/files/4747817/bsnes.zip)

**Comment by Kawa-oneechan** [comment]
As for *why* it fails...

`cp -a bsnes/out/bsnes bsnes-nightly/bsnes.exe`

I dunno, but I feel like a Windows-targeting compilation would result in a `bsnes.exe`.

**Comment by RokkumanX** [comment]
Thank you so much!!

**Comment by RokkumanX** [comment]
It doesn't appear to launch @Kawa-oneechan when I double click the .exe, the mouse cursor spins for a few seconds but no window appears and no bsnes process is running.

**Comment by Screwtapello** [comment]
> I feel like a Windows-targeting compilation would result in a bsnes.exe.

You'd think that, but it certainly didn't do that previously. I'm gonna take a look.

**Comment by Kawa-oneechan** [comment]
> It doesn't appear to launch @Kawa-oneechan when I double click the .exe, the mouse cursor spins for a few seconds but no window appears and no bsnes process is running.

Worked on my machine.

**Comment by RokkumanX** [comment]
> Worked on my machine.

Well downloading the latest build from the buildbot fixed the issue for me @Kawa-oneechan .

Thanks for solving the issue with the buildbot @Screwtapello , everything now works great!

![Great](https://user-images.githubusercontent.com/50436544/84102668-63938680-aa11-11ea-92c3-f27037ef8edd.jpg)
