### ISSUE TITLE
Question: what does the "No sprite limit" option do exactly?

### ISSUE THREAD

**Issue by Nix40** [bsnes-emu/bsnes#273]
This isn't an issue, just a question. On the enhancements tab there's the "No sprite limit" option. Does it remove the 32 sprites per scanline limit, allowing up to 128 to show on a scanline at the same time, or does it remove the 128 sprites per frame limit, allowing unlimited sprites to show at any frame?

**Comment by Kawa-oneechan** [comment]
The former. There's only enough OAM for 128 entries so it can't be the latter.

**Comment by Nix40** [comment]
All right, thanks for making it clear. Guess I'll close the thread now.
