### ISSUE TITLE
QWidget::paintEngine: Should no longer be called

### ISSUE THREAD

**Issue by internet-police** [bsnes-emu/bsnes#284]
when running for the terminal, i get a lot of these messages: QWidget::paintEngine: Should no longer be called
also building with qt5 gave a lot of warnings about deprecated commands

**Comment by Screwtapello** [comment]
This is a symptom of issue #106. Unfortunately, the Qt5 backend for the hiro UI library has not been maintained as Qt5 has matured, and we don't know anybody who understands Qt5 and hiro well enough to update it.

If you know anyone willing and able to figure this out, we'd appreciate the help!

**Comment by remutro** [comment]
You can fix this message by altering line 8 in hiro/qt/widget/viewport.cpp to something like this:

qtViewport->setAttribute(Qt::WA_PaintOnScreen, QT_VERSION < 0x050000 ? true : false);

This attribute is needed for Qt4, but shouldn't be set for Qt5+.
