### ISSUE TITLE
Feature Request: Please add Blarggs NTSC SNES filters 

### ISSUE THREAD

**Issue by joepogo** [bsnes-emu/bsnes#289]
Is it possible to please add Blarggs NTSC filters options to BSNES like RF, Composite, S-Video and RGB?

These filters really make the games shine they way they were meant to be. 

Thank you for considering!

Edit*

@carmiker 
@Screwtapello 

I had a question for you guys as I know every once in a while you guys make commits with retroarch bsnes. 

Is bsnes constantly in some sort of weird 512x448 hi res mode or something even when most games should be in 256x224? 

The reason why I ask is because no NTSC filter shader seems to work on bsnes at all, even when you put it in rf which should really make everything "shimmery" if you know what I mean. 

It's almost like it ignores any NTSC aspect from shaders that have it. 

Being able to combine blarggs rf or composite filter would be great.

Hopefully I'm making sense.

**Comment by carmiker** [comment]
The NTSC filters should be fully operational in the standalone build of bsnes. I've just rebuilt it after a `make clean` to make sure, and I had no problems at all.

To answer some of your questions, bsnes using the accurate PPU always runs at an internal resolution of 512x448, but the fast PPU switches resolutions on the fly either for hi-res modes the original console supports, or the enhanced mode 7, in which case the resolution can go well beyond what the SNES was capable of. In bsnes-jg I removed the fast PPU and blargg's NTSC filter, and also reworked video output to make it easier for post-processing shaders to deal with.

If you're looking for the best experience with blargg's NTSC filter, then your best option is probably to use the standalone build.

**Comment by joepogo** [comment]
First, thank you so much for your time @carmiker ! If you 
didn't know already I've spoken back and forth with you on the nestopia jge issues thread so it's good to hear from you again. 😁

I use retroarch on series x so there's currently no way for me enjoy bsnes on anything else. 

And it makes sense now, as I'm using bsnes v115 core and it did indeed seem like it was running in a constant hi res mode. 

I know you've done quite a bit with bsnes jge as well and love your work. 

Is there a way to make it work for us? If no one wants to make changes to this mainline branch I can always get a compile if someone is willing to supply a patch. 

That's why really I sought you out mainly, you've always been polite and awesome to communicate with. So I was curious if you would be willing to help us out. 😁🤗

Anyways, thanks for your time and I hope you're doing well man.

**Comment by carmiker** [comment]
If you are using the libretro port, then the easiest way for you to get the resolution you want is to disable hires mode 7 and use the fast PPU. That will make it always run at the correct resolution. If you want to handle accurate PPU mode, the way I achieved my goal was to always run at 512 pixels wide, but adjust vertical resolution when necessary. In my case, this is friendlier to the post-processing shaders, though it could be different with libretro. If you're looking to add the NTSC filter to libretro, it should be possible to add that option fairly easily. It's something you may be able to do yourself assuming you have the right development environment to build for the Series X. I'd take a look at how the current settings work, and apply the same logic to the NTSC filter.

**Comment by carmiker** [comment]
No expertise required anymore, @joepogo. I've created a pull request that adds this functionality. It did indeed take more effort than enabling a setting.
