### ISSUE TITLE
Super Mario Kart will not load at all even with the dsp files inside the bsnes folder.

### ISSUE THREAD

**Issue by WhyModeratorsSuck** [bsnes-emu/bsnes#29]
I have tried for so long to get Super Mario Kart to load and it keeps saying that dsp1b.bin is missing even though it is in the folder and then the game does not load. I am disappointed at this gaping bug because I am not able to play Super Mario Kart.

**Comment by RokkumanX** [comment]
Could be that you have and is using the wrong DSP1 file.

As you can see here everything is in working order:

![Working](https://user-images.githubusercontent.com/50436544/84138059-f81bda00-aa4d-11ea-84d6-bb99cfb7bdc2.jpg)

My copy of Super Mario Kart is utilizing DSP1 and NOT DSP1**B**

1. Use a hash calculator such as HashCalc or something similar and get the SHA-256 checksum of your copy of Super Mario Kart, mine is c04f517c2675d7a8f3498d958f097443dfaa0e66606c69c59b58a915b3454973 and is matching the one in the manifest as seen in the screenshot.

2. Open up the Super Famicom.bml file from the Database folder in Notepad++ and search with your SHA-256 checksum and see if you get a match.
This way you can determine if you need the DSP1 and not DSP1**B**

You having and utilizing the wrong DSP1 file is the only thing I could think of right now.

**Comment by WhyModeratorsSuck** [comment]
I had the correct files, but they were in the same directory as bsnes.exe and not the Firmware folder. My bad.
