### ISSUE TITLE
Cannot Disable 2nd Controller Port

### ISSUE THREAD

**Issue by neko-js** [bsnes-emu/bsnes#293]
Is it not possible to disable the 2nd controller port? Some games think that a 2nd game controller is connected.

![image](https://github.com/bsnes-emu/bsnes/assets/40058557/73adbb09-351c-444f-84fe-cd4fcbd536d9)

**Comment by Kawa-oneechan** [comment]
Yeah, there probably _should_ be a "none" option there...

**Comment by Screwtapello** [comment]
That's just the list of "when this device is connected to this port, what should it's mappings be". The actual way to change what's in controller port 2 is to use the System → Controller Port 2 menu.

**Comment by Kawa-oneechan** [comment]
I'd like to retract my reply.

**Comment by neko-js** [comment]
Ah, I did not see that menu. Thank you!

![image](https://github.com/bsnes-emu/bsnes/assets/40058557/43a899cc-a97e-4830-a082-51f9a2d60524)
