### ISSUE TITLE
wdc65816: fix PLB wrapping in emulation mode

### ISSUE THREAD

**Issue by Screwtapello** [bsnes-emu/bsnes#299]
@asiekierka found [an issue in ares' WDC65816 emulation](https://github.com/ares-emulator/ares/pull/1277) and we can probably (hopefully) copy the fix from ares.

> > Regarding PLB, it looks like it reads from $200 and snes9x, mesen, bsnes, and the official CPU manual all got it wrong.
>
> Reproduced and verified on real hardware via https://github.com/gilyon/snes-tests

**Comment by Screwtapello** [comment]
Fixed in dab534b6584e4debef2c9572e6b6588a604d79a9.

**Comment by orbea** [comment]
@Screwtapello If this is fixed can you close the issue?

**Comment by Screwtapello** [comment]
Whoops, thanks for the reminder!
