### ISSUE TITLE
Restore real hardware issue notes

### ISSUE THREAD

**Issue by KungFuFurby** [bsnes-emu/bsnes#3]
The repository byuu/bsnes had a list of real hardware graphical glitches, not emulation bugs, (not transferred to the website) that had vanished recently. A good majority of these were initially noted by @Max833. These issues are useful for avoiding false positives and false negatives when reporting emulation bugs on a per-game basis.

**Comment by Max833** [comment]
Hi. I mirrored everything:

All closed issues (10 pages) : https://archive.is/jd5qL
All open issues: http://archive.is/wydg9

**Real hardware issues:** http://archive.is/gs5eL
All issues I reported: http://archive.is/wip/pGM4h

**Comment by KungFuFurby** [comment]
Thanks! I made a couple of additional notes on my end (Star Fox being found in the same page as Captain Tsubasa IV), and also accidentally forgot Shin Megami Tensei's audio popping. Closing since the real hardware issue notes are now archived.

**Comment by Max833** [comment]
Here is everything that is known: https://github.com/bsnes-emu/bsnes/issues/206
