### ISSUE TITLE
Black Screen for Super Mario Kart (USA) DSP1B

### ISSUE THREAD

**Issue by n3vu0r** [bsnes-emu/bsnes#30]
Hi, both games show the *known clean image* icon and while Super Mario Kart (USA) with DSP1 works, the variant using DSP1B gives a black screen. Using bsnes built against latest commit.

The game hashes shown by manifest viewer:
`sha256: 89ad4ba02a2518ca792cf96b61b36613f86baac92344c9c10d7fab5433bebc16` (DSP1)
`sha256: 76d293e5a772eb2f326e173eac62ca323873b1f329f9b935a97ba86974e1fcd5` (DSP1B)

**Update**: In higan built against latest commit both variants work.

**Comment by RokkumanX** [comment]
I know you said you have tested this with bsnes and higan but what about [ares](https://ares.dev/)?
Is it the same?

It's hard to keep track on all different kind of versions and releases byuu/near have made over the years but I think ares is his personal reboot focusing on accuracy, preservation and simplicity making it way more easy to use than higan.

**Comment by n3vu0r** [comment]
Yes, it's the same. The game:

`76d293e5a772eb2f326e173eac62ca323873b1f329f9b935a97ba86974e1fcd5`

works with higan and ares lucia. It doesn't work with bsnes.

**Comment by RokkumanX** [comment]
Thanks, I guess that my hunch was right regarding ares.

I'm starting to believe that what you experience in higan and ares is the correct behavior and that there is a bug with bsnes not letting you play the DSP1B version.

I have no idea what could be wrong though and I'm not involved with the project either.

I wish you luck with this!

**Comment by n3vu0r** [comment]
Thanks, then let's wait.

**Comment by RokkumanX** [comment]
How are you holding up @n3vu0r? It's been 10 fast days haven't it since you replied the last time?

I've been waiting here pretty much ON/OFF every day since I posted here 12 days ago and honestly I need a break, it feels like the project have frozen or something and nothing really happens now.

It sucks that I couldn't help you with this issue really.

Unless accuracy isn't a problem, just use ares or higan for all your Super Nintendo/Super Famicom needs and bsnes for Super Game Boy.

I hope everything works out for you!

**Comment by n3vu0r** [comment]
Hi @RokkumanX, thanks for taking care, it's not urgent and not a big issue. I'm fine playing the DSP1 (without B) game version with bsnes (higan and ares are too demanding for my current system). I hope this project won't freeze for good and bugs like this can be fixed in the future when people find some time. And take at least a small break ;)

**Comment by n3vu0r** [comment]
Hi @RokkumanX, I figured it out.

It's simply the outdated `boards.bml` shipped with bsnes which misses the `SHVC-1K1X-10` board definition.

Copying over `boards.bml` from higan and running `sourcery` fixes this issue:

```bash
cd bsnes
make -C sourcery install
cp '../higan/higan/System/Super Famicom/boards.bml' 'bsnes/target-bsnes/resource/system/boards.bml'
cp '../higan/icarus/Database/Super Famicom.bml' 'bsnes/Database/Super Famicom.bml' # For completeness only.
sourcery bsnes/target-bsnes/resource/{resource.bml,resource.cpp,resource.hpp}
make -C bsnes install
```

Above instructions are basically the manual step mentioned in #13. Btw, which pull requests where you referring to in that issue?

**Comment by Max833** [comment]
I compared both files.

ares has two more:  `SHVC-1K1X-10` and `SHVC-LJ3M-01` but there is one that's just in bsnes: `SHVC-2P3B-01`

**Comment by n3vu0r** [comment]
Good point. But there's even another prototype board that's just in bsnes:

`SHVC-4PV5B-01`

From TV Animation - Slam Dunk - Shuueisha Limited (Japan)
(copy boards.bml from ares v115 to bsnes and do `git diff`)

**Comment by Max833** [comment]
Oh, you are right. I compared bsnes with ares v114 instead of v115.

**Comment by Screwtapello** [comment]
Thank you very much everybody for doing all this research and figuring out what's going on. I've merged the PR and verified that SMK now runs correctly with the DSP1B firmware.
