### ISSUE TITLE
Hayazashi Nidan Morita Shougi 2 wont start

### ISSUE THREAD

**Issue by AntiGrieferGames** [bsnes-emu/bsnes#301]
It says:
Error: missing required data: arm6.program.rom
Error: missing required data: arm6.data.rom

Using the newest Nightly Build

**Comment by Screwtapello** [comment]
Yes. This game's AI player logic runs on an ARM6 CPU on the cartridge. We cannot provide a copy of that AI logic for copyright reasons, anymore than we can provide a copy of the `.sfc` file that runs on the SNES CPU.

The ARM6 data cannot be dumped from the cartridge with an ordinary dumping tool, it needs an electron microscope and much time and expertise. However, I'm told that data is out there on the Internet somewhere, although it might be called `st018.program.rom` and `st018.data.rom` instead.

**Comment by SecularSteve** [comment]
Apparently the ST-011 and ST-018 Enhancement Chips were not only very proprietary one-time solutions for these games by the SETA corporation, but their information is presumed to be lost for years.

It would take some rigorous reverse engineering to get these games compatible, even on the most accurate system.

The only thing that may clue you in are the results of the succesfully reverse-engineered ST-010 used in the F1 ROC II (AKA Exhaust Heat II) game that makes the CPU Drivers a bit better than most titles at the time.

Not only was it discovered that the algorithm in the Chip was underwhelwingly simple, but the game is nothing more than an F-Zero clone with a Formula/Le-Mans skin over it anyway.

Move on, there's better Shougi games online these days. This is only worth it for the novelty.
