### ISSUE TITLE
Windows nightly download broken

### ISSUE THREAD

**Issue by 007mesen** [bsnes-emu/bsnes#303]
Still using Near’s last build. Was going to update today and the windows nightly link is broken here.

**Comment by Screwtapello** [comment]
Specifically, https://github.com/bsnes-emu/bsnes/releases/download/nightly/bsnes-windows.zip doesn't work for you? What happens when you try?

**Comment by Alcaro** [comment]
That link says Not Found.

Maybe it only works for repo admins or something? Try it in a private tab.

**Comment by 007mesen** [comment]
> Specifically, https://github.com/bsnes-emu/bsnes/releases/download/nightly/bsnes-windows.zip doesn't work for you? What happens when you try?

Depends how you go there. Try opening the zip…

**Comment by Screwtapello** [comment]
I just re-ran the release script, and now the link in the README downloads a ZIP file with the expected contents, even when I'm logged out. Can anyone else confirm it works?

**Comment by 007mesen** [comment]
> I just re-ran the release script, and now the link in the README downloads a ZIP file with the expected contents, even when I'm logged out. Can anyone else confirm it works?

All fixed! Thanks!!

**Comment by 007mesen** [comment]
> I just re-ran the release script, and now the link in the README downloads a ZIP file with the expected contents, even when I'm logged out. Can anyone else confirm it works?

Heads up it generates a pre release! Cool see attached
![IMG_7062](https://github.com/bsnes-emu/bsnes/assets/131622115/c822c05a-6aef-46ea-be29-6ca57957c4e7)

**Comment by Screwtapello** [comment]
Yep, nightlies are not final releases, so they're supposed to be pre-releases. Thanks for checking!
