### ISSUE TITLE
Assault Suits Valken - game restarts after introduction

### ISSUE THREAD

**Issue by ghost** [bsnes-emu/bsnes#305]
Hello. `Assault Suits Valken (World) (Switch)` restarts immediately at the beginning of the first level.

[No-Intro entry](https://datomatic.no-intro.org/index.php?page=show_record&s=49&n=4338).

bsnes 9560959
Windows 10

**Comment by carmiker** [comment]
Does it work on real SNES/SFC hardware using an SD2SNES or similar?
