### ISSUE TITLE
SA-1 DMA won't transfer to bank 0x41

### ISSUE THREAD

**Issue by Fernap** [bsnes-emu/bsnes#309]
Any attempts to use SA-1 side DMA to BWRAM with a destination in bank 0x41 will result in a transfer to the corresponding address at bank 0x40 instead.  Changing [line 6 in bsnes/sfc/coprocessor/sa1/dma.cpp](https://github.com/bsnes-emu/bsnes/blob/master/bsnes/sfc/coprocessor/sa1/dma.cpp#L6) from a `uint16` to a `uint24` should fix the problem (the SNES dev manual indicates 18 bits are actually used).  This bug was apparently introduced [here](https://github.com/bsnes-emu/bsnes/commit/a3e0f6da251aef0da53e7b2b6b14ba9d12eb3bc2#diff-d39fa44de6d269dcff133bcb1341b4ea71857980d5e911d3cda20d32e01d05d4).

Credit to @VitorVilela7 and @TheLX5 for originally diagnosing the problem, and Vitor for tracking down when the regression was introduced.

**Comment by orbea** [comment]
Do you happen to have a test case?

**Comment by Fernap** [comment]
Ultimately, finding this came from some custom code for handling dynamic sprites used in Vitor's SA-1 enhancement patch for SMW.  You can see an example of the code used [here](https://github.com/VitorVilela7/SMW-SA1-Pack/blob/master/asm/engine/snes_nmi.asm#L215-L230), among a few other spots; `!DSX_BUFFER` is a define set to $418000.  However, the actual DMA transfers to $408000 instead.

Is that sufficient, or were you looking more for a test ROM of some sort?

**Comment by carmiker** [comment]
A test ROM would always be helpful. The only reference I see to anything 18-bit in the manual is related to the Timer Circuit, in Book 2, [Page 1-2-2](https://archive.org/details/SNESDevManual/book2/page/n13/mode/2up). On the other hand I do see that DDA is a 24-bit register on [Page 1-4-22](https://archive.org/details/SNESDevManual/book2/page/n43/mode/2up). So I believe using a `uint24` here is indeed correct.

**Comment by Fernap** [comment]
Sorry, the 18 bit size I was getting was from table 1-9-2 on page 1-9-3.  Presumably it says 18 bits because that's the maximum possible size of BW-RAM, even if DDA is 24 bits.

**Comment by VitorVilela7** [comment]
SA-1 DMA should work for banks $40-$43, it's documented on SA-1 dev book. I
recommend changing the register to 24-bit.

I don't have a test ROM available right now but I can test this in the
nearby future.

Vitor

Em dom., 14 de jan. de 2024, 00:36, Fernap ***@***.***>
escreveu:
