### ISSUE TITLE
MD5 hash is different

### ISSUE THREAD

**Issue by recolorofkirby** [bsnes-emu/bsnes#313]
The MD5 hash of BSNES for Linux on the [website](https://bsnes.org/download/linux) is: `125a1f398641f972b707235ca926da93`

![Screenshot 2024-03-12 at 22-50-54 Download BSNES for Linux](https://github.com/bsnes-emu/bsnes/assets/163146652/f259059e-6114-4ca5-ade9-e3b5e2340240)

After I downloaded, I checked the hash by `md5sum`

```
$ md5sum bsnes-ubuntu.zip
```

The output is:

```
c8ae254d243d9536ef68457dc633536a  bsnes-ubuntu.zip
```

not the same as the one on the website.

**Comment by Kawa-oneechan** [comment]
Which website?

**Comment by recolorofkirby** [comment]
This https://bsnes.org/download/linux

**Comment by Screwtapello** [comment]
Yes, that website is out of our control. Don't trust anything it says.

**Comment by recolorofkirby** [comment]
Isn't this something official or community-driven? What annoying site. I'm sorry for lacking consideration and bringing up this issue to you.
