### ISSUE TITLE
CX4 games stuttering in LLE mode with libretro core

### ISSUE THREAD

**Issue by richterdeveloper** [bsnes-emu/bsnes#319]
Since Hayazashi Nidan Morita Shougi 1 and 2 are playable in the lastest libretro core version, the CX4 games in LLE mode are stuttering at the the presentation screen (the "X" 3D title animation in Megaman X2 and X3 are stuttering). Also, the bottom messages animations in RetroArch are stuttering too in LLE Enhancement Chips mode.

**Comment by Alcaro** [comment]
Isn't that chip the most cpu intensive to emulate of them all?

Not much we can do here. Switch to HLE or overclock your CPU.

**Comment by richterdeveloper** [comment]
I'm checking my configuration and the problem is the config file. I delete that config file and use de default generated from Retroarch and the problem was solved. Sorry for the false alarm.

**Comment by orbea** [comment]
@Screwtapello According to the previous comment the problem was solved by a Retroarch config change, maybe this should be closed? Not enough information to diagnose anyways.
