### ISSUE TITLE
(Feature Request) Force SuperFX / SuperFX 2 toggles?

### ISSUE THREAD

**Issue by Shooting-Starr** [bsnes-emu/bsnes#53]
I would like to see the ability to force SuperFX 1 or SuperFX 2 in any SuperFX games, as I think this is a feature much older versions of BSNES had. To clarify: I'd like the ability to force either SuperFX revision in any game, allowing me to say... either force SuperFX 2 in the first Star Fox, or force SuperFX 1 in Yoshi's Island.

**Comment by Screwtapello** [comment]
As far as I understand, the only difference between the SuperFX 1 and the SuperFX 2 is the clockspeed (10.7MHz versus 21MHz). As a result, you can "force" SuperFX 2 mode on a SuperFX 1 game by dragging the SuperFX overclocking slider to 200%.

That doesn't allow forcing SuperFX 1 mode on a SuperFX 2 game (the overclocking slider only goes down to 100%, not 50%), but I'm having a hard time imagining why that might be useful or helpful.

Feel free to reopen if there's a specific reason to halve the SuperFX speed.
