### ISSUE TITLE
Could you make an Android version?

### ISSUE THREAD

**Issue by Wesleyjor6** [bsnes-emu/bsnes#57]
oh well, you could make an android version since most of them play snes via emulator and Android devices

**Comment by kode54** [comment]
[citation needed]

**Comment by IamRifki** [comment]
https://twitter.com/iamdevloper/status/1194562654284787712

**Comment by DerKoun** [comment]
Doesn't Retroarch cover the whole "bsnes on mobile" thing?

**Comment by Wesleyjor6** [comment]
Infelizmente não

**Comment by Screwtapello** [comment]
OK people, please stop taunting the Android user.

As fast as bsnes is, it's still too intensive to give a good experience on mobile platforms. That said, I'm pretty sure RetroArch builds the bsnes core for Android, so you can try it out if you really, really want.

If somebody wants to *make* an Android version, my suggestion is to write a front-end for the libretro build, or use it as an example for how to use bsnes' internal emulation core API (which is basically the same as higan v106 and below, I believe). If it fits in neatly with the existing codebase and we can set up CI for it, we might take a PR, but I don't believe we'll ever get around to making an Android port ourselves.

**Comment by davidhedlund** [comment]
* https://github.com/libretro/bsnes-libretro/issues/2
