### ISSUE TITLE
Linux compilation?

### ISSUE THREAD

**Issue by Achaean** [bsnes-emu/bsnes#59]
I'm probably missing something, but what are the compilation instructions for Linux?

**TIA!**

BTW. The Discussion Forum registration, seems to be broken. The "word" is not accepted (although I pasted it from FAQ).

**Comment by Kawa-oneechan** [comment]
I just registered a test account just fine, including the word. Are you sure you had the *whole* thing and *only* the thing?

**Comment by Achaean** [comment]
Oh...got it!  ;-)
I entered 1 word (instead of 2).
I admit, it wasn't very clear.to me.

**Comment by Kawa-oneechan** [comment]
On the one hand, bold type is apparently not clear enough for some people. On the other hand, if you make it stand out too much you don't need to actually read the FAQ to spot the word 🤔

**Comment by Screwtapello** [comment]
Right now, the most reliable compilation instructions are [in the CI script](https://github.com/bsnes-emu/bsnes/blob/master/.cirrus.yml#L5-L9).

I filed #60 to remind us to write actual docs at some point.
