### ISSUE TITLE
Merge emulation fixes from higan

### ISSUE THREAD

**Issue by Screwtapello** [bsnes-emu/bsnes#61]
A few minor emulation fixes have landed in higan since bsnes was forked. We should cherry-pick those fixes across to maintain parity. You can generate a list of candidates in the higan repository with `git log v110.. higan/sfc` (assuming byuu already synced any changes from the fork-point to v110), but as of this writing they include:

- [X] https://github.com/higan-emu/higan/commit/caed1556ebb460cee27589bac7bdf9b0567a88e1
- [x] https://github.com/higan-emu/higan/commit/56bdd466461201f80001cc9db4bded1360e81336
- [ ] https://github.com/higan-emu/higan/commit/e422ddc7293b10aae8a1935d4c7f96aeb8445430

(I'm not sure about that middle one, but it's worth investigating)

**Comment by Screwtapello** [comment]
These fixes may allow us to remove game-specific workarounds in bsnes, too.

**Comment by Kawa-oneechan** [comment]
This gets my vote.

**Comment by Max833** [comment]
Great idea. And we shouldn't forget the mosaic fixes that went into ares but not bsnes. This is the mosaic test (ares is now hardware accurate):
https://github.com/PeterLemon/SNES/tree/master/PPU/Mosaic/Mode5

![image](https://user-images.githubusercontent.com/53529402/93684380-9be63e80-faaf-11ea-8c6c-f18c059b0531.png)

**Comment by Kawa-oneechan** [comment]
Ooh, good call.

**Comment by Screwtapello** [comment]
It's been pointed out to me that https://github.com/higan-emu/higan/commit/caed1556ebb460cee27589bac7bdf9b0567a88e1 is already changed in bsnes, so that's one down, I guess.

**Comment by rtretiakov** [comment]
I've added 56bdd46 to my fork and will be making a pull request.

**Comment by Screwtapello** [comment]
Just going by commit messages, the SNES mosaic fixes were in https://github.com/higan-emu/higan/commit/73b52e4d34b5edde080a32a16ca35cbdced437be and https://github.com/higan-emu/higan/commit/8b493a71960cf43e8b2dfbcddb4bc8a24bdd08a5.

**Comment by rtretiakov** [comment]
Thank you @Screwtapello , I will see about merging those fixes as well as the input one after some more analysis.

**Comment by Screwtapello** [comment]
Thank *you* for looking into it!

**Comment by rtretiakov** [comment]
https://github.com/bsnes-emu/bsnes/pull/66 contains the mosiac fixes.

**Comment by asuramaru** [comment]
> It's been pointed out to me that [higan-emu/higan@caed155](https://github.com/higan-emu/higan/commit/caed1556ebb460cee27589bac7bdf9b0567a88e1) is already changed in bsnes, so that's one down, I guess.

bsnes used game hacks ("fast joypad polling") to work around the bug that need to be removed now. bsnes still left the polling starting 256 cycles too soon for most games, and used a different incorrect hack for the games where this caused problems. So in a way, it's twice as broken as higan is now.

https://github.com/bsnes-emu/bsnes/blob/master/bsnes/target-bsnes/program/hacks.cpp#L17

Ideally, jbo-85's fix (https://github.com/higan-emu/higan/pull/90) to delay the start of polling for 256 cycles in higan needs to be ported back over, and then the "fast joypad polling" code and the hacks should be removed.

**Comment by rtretiakov** [comment]
@asuramaru thank you for pointing this out. I was looking at the other fix and trying to figure out how things add up. I think I have a better understanding now, and maybe will do that work when I get a chance.
