### ISSUE TITLE
Error when adding new cheat.

### ISSUE THREAD

**Issue by ekudritski** [bsnes-emu/bsnes#63]
I am using the latest nightly build.

Open any ROM.
Select Tools/Cheat Finder...
Press scan
Double click on any of the finds.
Enter a name and click Add.
You see wrong error message.
Remove empty line and press Add.

Problem is that that line does not filter out empty lines and then ``decodeSNES()`` reports an error.

https://github.com/bsnes-emu/bsnes/blob/a8c1f19f7512e38b73620875145b86e251721a0e/bsnes/target-bsnes/tools/cheat-editor.cpp#L104

**Comment by Screwtapello** [comment]
I can reproduce this error.

**Comment by Screwtapello** [comment]
Thank you very much for tracking down the error to the code that causes it, by the way!
