### ISSUE TITLE
[bsnes nightly build] SpellCraft - Aspects of Valor

### ISSUE THREAD

**Issue by Max833** [bsnes-emu/bsnes#86]
Looks like this issue still remains (https://archive.is/Mm4NZ#selection-1835.80-1835.141)

When you press b at this place, the password menu gets skipped sometimes. The same happens when you press b at the start - the new game starts immediately and you can't choose "continue game".

![11](https://user-images.githubusercontent.com/53529402/97790291-ad9b2580-1bc7-11eb-8737-b8a04f4cb5f2.png)
![22](https://user-images.githubusercontent.com/53529402/97790292-aecc5280-1bc7-11eb-841b-9971c2b1e50d.png)
![image](https://user-images.githubusercontent.com/53529402/97790345-3f0a9780-1bc8-11eb-9660-901ce1cfe8eb.png)

**Comment by Screwtapello** [comment]
Thank you, Max, for all your help with testing!

Some quick thoughts off the top of my head:

- I'm sure you've already tested this on hardware, but I'd like to hear somebody say "yes, I've tested this on hardware and it works as expected"
- @asuramaru said that their fix in bsnes was subtly different from @jbo-85's fix in higan, and if a game ever worked in one but not the other, that would be a clue to which implementation was more correct

**Comment by asuramaru** [comment]
Yes if you can please confirm if it runs for you in higan-nightly that'd be a big help!

Unless someone beats me to this, I feel kinna responsible so I'll volunteer to take on this issue.

**Comment by Max833** [comment]
Hey guys. You are welcome. Yeah, I have tested this on hardware and everything is working there. It does work with Mesen-S and Snes9X as well, but like byuu said... that's probably because they don't emulate this joypad behaviour. Higan (nightly build) has the same problem. So it looks like the different implementation approach isn't the problem in this case.

**Comment by asuramaru** [comment]
I fixed it :heart:

**Comment by Screwtapello** [comment]
I've taken Asura's patch, tidied up the commit message a little, and made a new PR since Asura closed their old one.

**Comment by Max833** [comment]
It works great now. Thank you! =)
